CREATE TABLE MSU_SUTULAA.EMPLOYEES AS SELECT * FROM HR.EMPLOYEES;

CREATE TABLE MSU_SUTULAA.DEPARTMENTS AS SELECT * FROM HR.DEPARTMENTS;

CREATE TABLE MSU_SUTULAA.JOBS AS SELECT * FROM HR.JOBS;

CREATE TABLE MSU_SUTULAA.JOB_HISTORY AS SELECT * FROM HR.JOB_HISTORY;

CREATE TABLE MSU_SUTULAA.JOB_GRADES AS SELECT * FROM HR.JOB_GRADES;

CREATE TABLE MSU_SUTULAA.LOCATIONS AS SELECT * FROM HR.LOCATIONS;

CREATE TABLE MSU_SUTULAA.COUNTRIES AS SELECT * FROM HR.COUNTRIES;

CREATE TABLE MSU_SUTULAA.REGIONS AS SELECT * FROM HR.REGIONS;

----primary keys
ALTER TABLE EMPLOYEES ADD CONSTRAINT pk_employees PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT pk_departments PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE JOBS ADD CONSTRAINT pk_jobs PRIMARY KEY (JOB_ID);

ALTER TABLE REGIONS ADD CONSTRAINT pk_regions PRIMARY KEY (REGION_ID);

ALTER TABLE COUNTRIES ADD CONSTRAINT pk_countries PRIMARY KEY (COUNTRY_ID);

ALTER TABLE LOCATIONS ADD CONSTRAINT pk_locations PRIMARY KEY (LOCATION_ID);

ALTER TABLE JOB_GRADES ADD CONSTRAINT pk_job_grades PRIMARY KEY (GRADE);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT pk_job_history PRIMARY KEY (START_DATE, EMPLOYEE_ID);

----foreign keys
ALTER TABLE EMPLOYEES 
ADD CONSTRAINT fk_department
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE EMPLOYEES 
ADD CONSTRAINT fk_manager
FOREIGN KEY(manager_id) REFERENCES EMPLOYEES(employee_id);

ALTER TABLE JOB_HISTORY ADD CONSTRAINT fk_jobs FOREIGN KEY(JOB_ID) REFERENCES JOBS(JOB_ID);

ALTER TABLE COUNTRIES ADD CONSTRAINT fk_regions
	FOREIGN KEY(region_id) REFERENCES REGIONS(region_id);

ALTER TABLE LOCATIONS REFERENCES ADD CONSTRAINT fk_countries
	FOREIGN KEY(country_id) REFERENCES COUNTRIES(country_id);

ALTER TABLE LOCATIONS ADD CONSTRAINT fk_countries
	FOREIGN KEY(country_id) REFERENCES COUNTRIES(country_id);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT fk_locations
    FOREIGN KEY(location_id) REFERENCES LOCATIONS(location_id);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT fk_employees
	FOREIGN KEY(manager_id) REFERENCES EMPLOYEES(employee_id);

ALTER TABLE EMPLOYEES ADD CONSTRAINT fk_jobs_id FOREIGN KEY(JOB_ID) REFERENCES JOBS(JOB_ID);

ALTER TABLE JOB_HISTORY  ADD CONSTRAINT fk_departments FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);

ALTER TABLE JOB_HISTORY  ADD CONSTRAINT fk_employees_id FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);