----1
SELECT CONCAT(CONCAT(LAST_NAME, ' | '), SALARY)AS WYNAGRODZENIE FROM EMPLOYEES WHERE (SALARY > 2000 AND SALARY <= 7000) AND (DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50) ORDER BY EMPLOYEES.LAST_NAME; 

----2
SELECT e.HIRE_DATE, e.LAST_NAME, e.SALARY FROM EMPLOYEES e 
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID 
WHERE EXTRACT(YEAR FROM m.HIRE_DATE) > 2005 ORDER BY e.SALARY;

----3
SELECT CONCAT(CONCAT(FIRST_NAME, ' | '), LAST_NAME)AS FULL_NAME, SALARY, PHONE_NUMBER FROM EMPLOYEES
WHERE (LAST_NAME LIKE '__%e%') AND (FIRST_NAME LIKE '%an%') ORDER BY FIRST_NAME DESC, LAST_NAME;

----4
SELECT e.FIRST_NAME, e.LAST_NAME, MONTHS_BETWEEN(MAX(j.END_DATE), MIN(j.START_DATE)) AS NUMBER_OF_MONTHS,
CASE WHEN MONTHS_BETWEEN(MAX(j.END_DATE), MIN(j.START_DATE)) <= 150 THEN e.SALARY * 0.10
WHEN MONTHS_BETWEEN(MAX(j.END_DATE), MIN(j.START_DATE)) BETWEEN 151 AND 200 THEN e.SALARY * 0.20
ELSE e.SALARY * 0.30
END AS BONUS
FROM EMPLOYEES e
JOIN JOB_HISTORY j ON e.EMPLOYEE_ID = j.EMPLOYEE_ID
GROUP BY e.FIRST_NAME, e.LAST_NAME, e.SALARY
ORDER BY NUMBER_OF_MONTHS;

----5
SELECT d.DEPARTMENT_NAME, round(SUM(e.SALARY)) AS suma, round(AVG(e.SALARY)) AS srednia 
FROM JOBS j
JOIN EMPLOYEES e ON j.JOB_ID = e.JOB_ID
JOIN DEPARTMENTS d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID 
WHERE j.MIN_SALARY > 5000
GROUP BY d.DEPARTMENT_NAME;

----SPRAWDZENIE
SELECT d.DEPARTMENT_NAME, j.JOB_TITLE, j.MIN_SALARY FROM DEPARTMENTS d 
JOIN EMPLOYEES e ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN JOBS j ON e.JOB_ID = j.JOB_ID
HAVING MIN(j.MIN_SALARY) > 5000
GROUP BY d.DEPARTMENT_NAME, j.JOB_TITLE, j.MIN_SALARY;

----6

SELECT e.LAST_NAME, e.DEPARTMENT_ID, e.JOB_ID FROM EMPLOYEES e 
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON l.LOCATION_ID = d.LOCATION_ID
WHERE l.CITY = 'Toronto'
GROUP BY e.LAST_NAME, e.DEPARTMENT_ID, e.JOB_ID;

----7
SELECT e.FIRST_NAME, e.LAST_NAME, c.FIRST_NAME, c.LAST_NAME FROM EMPLOYEES e
JOIN EMPLOYEES c ON c.MANAGER_ID = e.MANAGER_ID
WHERE e.FIRST_NAME = 'Jennifer' AND e.EMPLOYEE_ID != c.EMPLOYEE_ID
GROUP BY e.FIRST_NAME, e.LAST_NAME, c.FIRST_NAME, c.LAST_NAME;

----8
SELECT d.DEPARTMENT_ID, d.DEPARTMENT_NAME FROM EMPLOYEES e 
RIGHT JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_ID, d.DEPARTMENT_NAME
HAVING COUNT(e.EMPLOYEE_ID) = 0;

----9
SELECT e.FIRST_NAME, e.LAST_NAME, e.JOB_ID, d.DEPARTMENT_NAME, e.SALARY, j.GRADE
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN JOB_GRADES j ON e.SALARY BETWEEN j.MIN_SALARY AND j.MAX_SALARY
ORDER BY j.GRADE;

----10
SELECT e.FIRST_NAME, e.LAST_NAME, e.SALARY FROM EMPLOYEES e
WHERE e.SALARY > (SELECT AVG(em.SALARY) FROM EMPLOYEES em)
GROUP BY e.FIRST_NAME, e.LAST_NAME, e.SALARY
ORDER BY e.SALARY DESC;

----11
SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, c.LAST_NAME FROM EMPLOYEES e 
JOIN EMPLOYEES c ON e.MANAGER_ID = c.MANAGER_ID
WHERE (c.LAST_NAME LIKE '%u%') AND (e.DEPARTMENT_ID = c.DEPARTMENT_ID) AND (e.EMPLOYEE_ID  != c.EMPLOYEE_ID);